name: Events Example

on:
  push:
    branches:
      - newbranch
      - ahmed

    
jobs:
  printHelloWorld:
    runs-on: ubuntu-latest
    steps: 
      - name: first step
        run: echo "Ahmed's branch works well"

        